services:
  mongo:
    image: mongo:6.0
    container_name: mongodb-movie-api
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: movie-rest-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGO_DB_URI: mongodb://mongo:27017/expressApi

volumes:
  mongo-data:
